version: '3'

services:
  app:
    image: 'talos:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: 'postgres:12.1-alpine'
    container_name: db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=talos
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432